"""Shared constants for data sources and topic presets."""

TOPIC_PRESETS = {
  "Health & disease": [
    "GENERAL_HEALTH",
    "MEDICAL",
    "DISEASE",
    "PUBLIC_HEALTH",
    "WB_621_HEALTH_NUTRITION_AND_POPULATION",
    "WB_1406_DISEASES",
    "WB_1430_MENTAL_HEALTH",
    "CRISISLEX_C03_WELLBEING_HEALTH",
  ],
  "COVID & coronavirus": ["COVID", "COVID-19", "CORONAVIRUS", "SARS_COV_2", "SARS-COV-2"],
  "Cholera": ["CHOLERA"],
  "Ebola": ["EBOLA"],
  "Dengue": ["DENGUE"],
  "Malaria": ["MALARIA"],
  "Diphtheria": ["DIPHTHERIA"],
  "Tuberculosis": ["TUBERCULOSIS"],
  "Measles": ["MEASLES"],
  "Mpox": ["MPOX", "MONKEYPOX"],
  "Vaccination & immunization": ["VACCINE", "VACCINATION", "IMMUNIZATION", "PUBLIC_HEALTH", "MEDICAL"],
  "Hospitals & healthcare": ["GENERAL_HEALTH", "MEDICAL", "PUBLIC_HEALTH", "HOSPITAL", "CLINIC", "PHYSICIAN", "NURSE"],
  "Water, sanitation & hygiene": ["WATER", "SANITATION", "HYGIENE", "CHOLERA", "CRISISLEX_C06_WATER_SANITATION"],
  "Natural disasters": [
    "NATURAL_DISASTER",
    "NATURAL_DISASTER_FLOOD",
    "NATURAL_DISASTER_FLOODS",
    "NATURAL_DISASTER_EARTHQUAKE",
    "WILDFIRE",
    "MANMADE_DISASTER_IMPLIED",
    "CRISISLEX_CRISISLEXREC",
  ],
  "Flooding": ["NATURAL_DISASTER_FLOOD", "NATURAL_DISASTER_FLOODS", "FLOOD", "FLASH_FLOOD", "INUNDATION"],
  "Earthquakes": ["NATURAL_DISASTER_EARTHQUAKE", "EARTHQUAKE", "SEISMIC"],
  "Wildfires": ["WILDFIRE", "FIRE"],
  "Industrial accidents": ["MANMADE_DISASTER_IMPLIED", "INDUSTRIAL", "ACCIDENT", "EXPLOSION", "CHEMICAL_SPILL", "MINE_ACCIDENT"],
  "Conflict & violence": [
    "ARMEDCONFLICT",
    "MILITARY",
    "KILL",
    "CEASEFIRE",
    "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE",
    "WB_2433_CONFLICT_AND_VIOLENCE",
  ],
  "Protests & unrest": ["PROTEST", "RIOT", "STRIKE", "DEMONSTRATION", "UNREST"],
  "Humanitarian aid": ["HUMANITARIAN", "AID", "RELIEF", "FOOD_AID", "CRISISLEX_CRISISLEXREC"],
  "Migration & refugees": ["MIGRATION", "REFUGEE", "DISPLACED", "ASYLUM", "WB_2837_IMMIGRATION"],
  "Food security": ["FOOD_SECURITY", "MALNUTRITION", "HUNGER", "FAMINE", "FOOD"],
  "Economy & inflation": ["ECON_INFLATION", "EPU_ECONOMY", "EPU_ECONOMY_HISTORIC", "ECON_DEBT", "WB_450_DEBT", "PRICE"],
  "Elections & politics": ["ELECTION", "GENERAL_GOVERNMENT", "EPU_POLICY_CONGRESS", "LEGISLATION", "WB_831_GOVERNANCE"],
  "Crime & corruption": ["ARREST", "TRIAL", "SOC_GENERALCRIME", "WB_1014_CRIMINAL_JUSTICE", "CORRUPTION", "POLICE"],
}

COUNTRY_LOOKUP_URL = "https://www.gdeltproject.org/data/lookups/FIPS.country.txt"
CAMEO_LOOKUP_URL = "https://www.gdeltproject.org/data/lookups/CAMEO.eventcodes.txt"
GKG_THEMES_LOOKUP_URL = "https://data.gdeltproject.org/api/v2/guides/LOOKUP-GKGTHEMES.TXT"

# Static GKG theme catalog snapshot to avoid expensive live catalog scans.
STATIC_GKG_THEME_CATALOG_DATE = "2026-04-13"
STATIC_GKG_THEME_CATALOG = [
  {"Topic Group": "Health & Disease", "Topic Label": "GENERAL_HEALTH"},
  {"Topic Group": "Health & Disease", "Topic Label": "MEDICAL"},
  {"Topic Group": "Health & Disease", "Topic Label": "DISEASE"},
  {"Topic Group": "Health & Disease", "Topic Label": "EPIDEMIC"},
  {"Topic Group": "Health & Disease", "Topic Label": "PANDEMIC"},
  {"Topic Group": "Health & Disease", "Topic Label": "PUBLIC_HEALTH"},
  {"Topic Group": "Health & Disease", "Topic Label": "WB_621_HEALTH_NUTRITION_AND_POPULATION"},
  {"Topic Group": "Health & Disease", "Topic Label": "WB_1430_MENTAL_HEALTH"},
  {"Topic Group": "Conflict & Security", "Topic Label": "ARMEDCONFLICT"},
  {"Topic Group": "Conflict & Security", "Topic Label": "MILITARY"},
  {"Topic Group": "Conflict & Security", "Topic Label": "KILL"},
  {"Topic Group": "Conflict & Security", "Topic Label": "CEASEFIRE"},
  {"Topic Group": "Conflict & Security", "Topic Label": "SECURITY_SERVICES"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "NATURAL_DISASTER_FLOOD"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "NATURAL_DISASTER_FLOODS"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "NATURAL_DISASTER_EARTHQUAKE"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "WILDFIRE"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "CRISISLEX_C03_WELLBEING_HEALTH"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "CRISISLEX_T03_DEAD"},
  {"Topic Group": "Disasters & Crisis", "Topic Label": "CRISISLEX_C07_SAFETY"},
  {"Topic Group": "Economy & Markets", "Topic Label": "ECON_INFLATION"},
  {"Topic Group": "Economy & Markets", "Topic Label": "ECON_DEBT"},
  {"Topic Group": "Economy & Markets", "Topic Label": "EPU_ECONOMY"},
  {"Topic Group": "Economy & Markets", "Topic Label": "EPU_POLICY_SPENDING"},
  {"Topic Group": "Economy & Markets", "Topic Label": "WB_450_DEBT"},
  {"Topic Group": "Politics & Governance", "Topic Label": "ELECTION"},
  {"Topic Group": "Politics & Governance", "Topic Label": "LEGISLATION"},
  {"Topic Group": "Politics & Governance", "Topic Label": "GENERAL_GOVERNMENT"},
  {"Topic Group": "Politics & Governance", "Topic Label": "EPU_POLICY_CONGRESS"},
  {"Topic Group": "Politics & Governance", "Topic Label": "WB_831_GOVERNANCE"},
  {"Topic Group": "Society & Humanitarian", "Topic Label": "HUMANITARIAN"},
  {"Topic Group": "Society & Humanitarian", "Topic Label": "REFUGEE"},
  {"Topic Group": "Society & Humanitarian", "Topic Label": "MIGRATION"},
  {"Topic Group": "Society & Humanitarian", "Topic Label": "FOOD_SECURITY"},
  {"Topic Group": "Society & Humanitarian", "Topic Label": "MALNUTRITION"},
  {"Topic Group": "Crime & Law", "Topic Label": "ARREST"},
  {"Topic Group": "Crime & Law", "Topic Label": "TRIAL"},
  {"Topic Group": "Crime & Law", "Topic Label": "SOC_GENERALCRIME"},
  {"Topic Group": "Crime & Law", "Topic Label": "WB_1014_CRIMINAL_JUSTICE"},
  {"Topic Group": "Infrastructure & Environment", "Topic Label": "WB_135_TRANSPORT"},
  {"Topic Group": "Infrastructure & Environment", "Topic Label": "INFRASTRUCTURE"},
  {"Topic Group": "Infrastructure & Environment", "Topic Label": "ENERGY"},
  {"Topic Group": "Media & Information", "Topic Label": "MEDIA"},
  {"Topic Group": "Media & Information", "Topic Label": "SOCIAL_MEDIA"},
]
